### ISSUE TITLE
Exporting as text and screenshot.

### ISSUE THREAD

**Issue by MohaimenH** [MohaimenH/Venn#10]
Data needs to be exported as a text file. Need to work on different formats and formatting of text itself.

Need to add snapshot functionality.

**Comment by MohaimenH** [comment]
Added both of the features but they need great improvements.

**Comment by MohaimenH** [comment]
Screenshot now works better. Has all the required elements in the screenshot, nothing more.

**Comment by li-jiahao-216263949** [comment]
Now the export file is consistent with import file. And both function is availble for file chooser. The PathNotFound Exception is no longer needed.
