### ISSUE TITLE
(bug) Bug Report - Element intersects between two Venn Circles  

### ISSUE THREAD

**Issue by lukas-rose-216489023** [MohaimenH/Venn#12]
Bug Report 
========

Bug Name 
-------------
Venn - Element intersects between two Venn Circles  

Product
------------
venn.jar

Summary
-------------
When the user inputs a long text element into a section of the Venn diagram, the middle section used in my case, the scroll function appears for the longer element. When the user uses this option the very top element in the section, where the user is scrolling, gets scrolled over the edge of the Venn circle.

Severity
-------------
S1

Priority
-------------
P1

Submit Date
-------------
March 14, 2020         

Reporter
-------------
Lukas Rose       
lukayork@my.yorku.ca   

Platform
-------------
Microsoft Surface Pro   
             
OS
-------------
Windows 10 Version 1909
   
Processor
-------------
Intel(R) Core(TM) i5-6300U 

Java Version
-------------
JDK 13.0.2    
     

Description
===========

Steps to reproduce
------------------
1. Run venn.jar
2. Select the "Please Type Elements.." text box and write "This is a  bug"
3. Select 'Add'
4. Drag the element and drop in the middle section of Venn diagram
5. Repeat steps 2 to 4, but add the text "This is a bug that runs over the edge"
6. Use the horizontal scroll bar 

Expected result
---------------
Horizontally scrolls across the text elements and cuts of the text elements before it touches the edge of the circle section it is in.

Actual result
-------------
Horizontally scrolls across the text elements and cuts of the text before it touches the edge except for the very top element of the circle section. This element gets cut off after it went over the edge of the section.

Screenshot
----------
[
![image](https://user-images.githubusercontent.com/46407773/76689141-5ed55700-6609-11ea-8ed9-13510544db55.png)
](url)

**Comment by MohaimenH** [comment]
Thanks for your feedback.

ListViews are not present in the new version anymore, so the bug is no longer present.

Fixed and closed.
