### ISSUE TITLE
(bug) Bug Report - Window Resizing Error 

### ISSUE THREAD

**Issue by lukas-rose-216489023** [MohaimenH/Venn#13]
Bug Report 
========

Bug Name 
-------------
Venn - Window Resizing Error

Product
------------
venn.jar

Summary
-------------
When the user opens the Venn system and tries to resize the window smaller the Venn Diagram and all other components do not resize and go off the window screen.

Severity
-------------
S2

Priority
-------------
P2

Submit Date
-------------
March 14, 2020         

Reporter
-------------
Lukas Rose   
lukayork@my.yorku.ca       

Platform
-------------
Microsoft Surface Pro       
             
OS
-------------
Windows 10 Version 1909
   
Processor
-------------
Intel(R) Core(TM) i5-6300U 

Java Version
-------------
JDK 13.0.2    
   

Description
===========

Steps to reproduce
------------------
1. Run venn.jar
2. Resize the window by pressing a corner of the window and moving it inwards the window.

Expected result
---------------
Resizes the window and the components of the system so the format and layout of the program do not get changed but only resized.

Actual result
-------------
Resizes the program window. It does not resize the program's components and stays in the same position causing components to go off the window.

Screenshot
----------
[
![image](https://user-images.githubusercontent.com/46407773/76689531-2fc0e480-660d-11ea-8d93-570d2981c0bd.png)
](url)

**Comment by MohaimenH** [comment]
Thanks for the feedback.

Added minimum height/width, so components do not go off the window.

Fixed and closed.
