### ISSUE TITLE
(enhancement) Bug Report - Export as Image with a large text element error

### ISSUE THREAD

**Issue by lukas-rose-216489023** [MohaimenH/Venn#14]
Bug Report 
========

Bug Name 
-------------
Venn - Export as Image with a large text element error

Summary
-------------
When the user exports the Venn diagram as a JPEG image the image does not show the whole text element but only to where the user currently scrolled to.

Severity
-------------
S3

Priority
-------------
P3

Submit Date
-------------
March 14, 2020         

Reporter
-------------
Lukas Rose          

Platform
-------------
Microsoft Surface Pro       
             
OS
-------------
Windows 10 Version 1909
   
Processor
-------------
Intel(R) Core(TM) i5-6300U 

Java Version
-------------
JDK 13.0.2     

Description
===========

Steps to reproduce
------------------
1. Run venn.jar
2. Insert a large text element into any section so that a horizontal scroll bar appears
3. Click 'Export'
4. Click 'As JPEG Image (.jpg)'

Expected result
---------------
The saved image of the Venn diagram includes all the elements of the diagram. This includes the title of the diagram, titles of sections, and the text elements.

Actual result
-------------
The saved image of the Venn diagram included all the elements of the diagram except for the event that the user has a long text element. The image does not show the whole text element in its section.

Screenshot
----------
[
![image](https://user-images.githubusercontent.com/46407773/76689738-5253fd00-660f-11ea-9d43-277fd318c629.png)
](url)

**Comment by MohaimenH** [comment]
Thanks for your feedback.

ListViews are not present in the new version anymore.

Fixed and closed.
