### ISSUE TITLE
(Enhancement) Resizing venn diagram

### ISSUE THREAD

**Issue by jdwalker17** [MohaimenH/Venn#15]
### Enhancement(resizing venn diagram)

- OS: Windows10

- Importance: P3

- Release Tested: v2

- Java Version: JDK 13.0.2

- Submit Date: 3/14/2020

### Description: 
When creating a new venn diagram, there is no way to resize each circle. This is not a bug but a potential enhancement. 
### Steps to produce: 

no steps to reproduce.
### Screenshot:

![P3G2B2](https://user-images.githubusercontent.com/51487947/76690448-5c2d2e80-6616-11ea-8d68-bf6554ce9bc2.png)

### Current Result: 
Each venn diagram has no function for resizing. No button is included with a sliding option.
### Enhanced Result: 
Each venn diagram circle could each have a slider button so user can specify size of each circle.

**Comment by MohaimenH** [comment]
Thanks for the feedback.

Added sliders for both circles.

Fixed and closed.
