### ISSUE TITLE
(Bug) dragging text objects outside edge of circle boundary 

### ISSUE THREAD

**Issue by jdwalker17** [MohaimenH/Venn#16]
### Bug (dragging text objects)

- OS: Windows10

- Importance: P4

- Release Tested: v2

- Java Version: JDK 13.0.2

- Submit Date: 3/14/2020

### Description: 
When text objects are dragged near the outside edge of the circle, the text can relocate back inside the circle
### Steps to produce: 

insert new text in text area (highlighted in red), when new text is added into secondary text area (highlighted in blue) then dragged to area just outside circle area (highlighted in green) objects are then placed inside circle. 

### Screenshot:

![P3G2B1](https://user-images.githubusercontent.com/51487947/76690581-df9b4f80-6617-11ea-9890-7298493f355a.png)

### Expected Result: 
Text object should remain outside the circle or back to secondary text area (highlighted in blue) after dragging each text object outside specified circle.
### Actual Result: 
Text object can relocate inside circle when not technically specified for that given circle.

**Comment by MohaimenH** [comment]
Thanks for your feedback.

The new version is completely based on drag and drop, hence the bug is not present anymore.

Fixed and closed.
