### ISSUE TITLE
(Bug) Resizing window does not scale text objects already inside venn diagram

### ISSUE THREAD

**Issue by jdwalker17** [MohaimenH/Venn#17]
### Bug (Resizing window doesnt scale text objects)

- OS: Windows10

- Importance: P4

- Release Tested: v2

- Java Version: JDK 13.0.2

- Submit Date: 3/14/2020

### Description: 
When the window of the venn diagram is resized, the current text objects do not scale inwards towards the smaller size of the window. 
### Steps to produce: 

Insert text in text area(highlighted in red), then once text is inserted into secondary text area(highlighted in blue) drag into example circle (highlighted in green). Then resize program window. When window goes past green box which represents text object, the object should then scale towards the inside of the window.

### Screenshot:

![P3G2B3](https://user-images.githubusercontent.com/51487947/76690731-892f1080-6619-11ea-87eb-228fa5a4972f.png)

### Expected Result: 
Text object should remain inside the circle after dragging window smaller.
### Actual Result: 
Text object will not re-scale and remain outside the resized window.

**Comment by MohaimenH** [comment]
Thanks for your feedback.

Added a minimum window size to ensure all the components are visible at all times.

Fixed and closed.
