### ISSUE TITLE
(Enhancement) Circle Color Change

### ISSUE THREAD

**Issue by sarwat12** [MohaimenH/Venn#18]
**OS used:** Linux
**Release tested:** Latest Release
**Java Version:** Java 12
**Description:** The option to change colors for circles opens up text boxes which requires the user to type in a color using Hexadecimal format, which many users may find inconvenient.
**Severity:** Minor
**Priority:** P4

**Steps to reproduce:**
1 - Open Venn application
2 - Click on the Edit tab on the top left corner of the UI
3 - Click Set A > Change Set Color

**Actual Results:** Text box pop up which requires users to enter color value
**Expected Results:** Visual options where the user is able to pick a color without entering any values

**Comment by MohaimenH** [comment]
Although inputting name of colors works as well, we intend to add a color picker.

Thanks for the feedback!

**Comment by MohaimenH** [comment]
Color picker added.

Fixed and closed.
