### ISSUE TITLE
(Bug) Export and Import Text File

### ISSUE THREAD

**Issue by sarwat12** [MohaimenH/Venn#20]
**OS used:** Linux
**Release tested:** Latest Release
**Java Version:** Java 12
**Description:** The operating system does not detect the creation of an exported text file while importing in the Venn application.
**Severity:** Normal
**Priority:** P3

**Steps to reproduce:**
1 - Open Venn application
2 - Click on the Export tab on the top left of the UI
3 - Click As Text File, and then save the newly created text file in any location
4 - Click the File tab on the top left of the UI
5 - Click on Import Text File

**Actual Results:** The newly created text file is unavailable, in the same previous saved location, for importing onto the currently running Venn Application
**Expected Results:** Successful import of the text file from the saved location

**Comment by li-jiahao-216263949** [comment]
The Export function contains two output method now:
1. readable text Report file
2. Save file which is xml format and it can be reloaded
