### ISSUE TITLE
(Enhancement) Dark Mode

### ISSUE THREAD

**Issue by gill-indermohan-216542045** [MohaimenH/Venn#21]
OS used: Mac
Release Tested: Latest Release
Java Version: Java 13
Description: Dark mode decreases visibility of some parts of the app.
Severity: Normal
Priority: P3

Steps to Produce: Open the app, click help, then click dark mode.

Expected Result: The colour format of the app turns darker whilst still being able to see all the items on the app at the same brightness. The text should be reasonably easy to see at the same brightness.

Actual Result: The app gets too dark, needing to change brightness to a higher level to see all the items on the screen (such as the text).

**Comment by MohaimenH** [comment]
Thanks for the feedback.

Fixed and closed.
