### ISSUE TITLE
Enhancement enable font size change of the text 

### ISSUE THREAD

**Issue by marcoywm** [MohaimenH/Venn#22]
OS used: Windows 10
Release tested: Latest Release
Java Version: Java 12
Description: the users could not change the font size once the label has been created
Severity: Minor
Priority: P4

Steps to reproduce:
1 - Open Venn application
2 - Type the text inside the text editor
3 - Click the add button below the text editor
4 - Once the text is added to the Drag & Drop Element field, drop the text label to the a circle
5 - The users should have the option to change the text label inside the circle

Actual Results: the user could not change the size of text label inside the circle
Expected Results: The size of label in side the A circle should be changed according the font size users enter.

**Comment by MohaimenH** [comment]
Can you please share a GIF of the bug?

**Comment by MohaimenH** [comment]
Thanks for your feedback.

To avoid going through same issue, this is being closed.
