### ISSUE TITLE
bug: set font option doesn't work 

### ISSUE THREAD

**Issue by marcoywm** [MohaimenH/Venn#23]
OS used: Windows 10
Release tested: Latest Release
Java Version: Java 12
Description: the users could not change the font once the label has been created
Severity: Minor 
Priority: P4

Steps to reproduce:
1 - Open Venn application
2 - Type the text inside the text editor
3 - Click the add button below the text editor
4 - Once the text is added to the Drag & Drop Element field, drop the text label to the a circle
5 - The user should have option change the font family of the text label inside the circles.

Actual Results: Users could not change font family the text inside the circle
Expected Results: The size of label in side the A circle should be changed according the font name users enter.

**Comment by MohaimenH** [comment]
Thanks for your feedback.

To avoid going through same issue, this is being closed.
