### ISSUE TITLE
(Bug) Item does not drop into the left circle correctly. 

### ISSUE THREAD

**Issue by Jihal** [MohaimenH/Venn#26]
Bug Description: Item does not drop into the correct circle.
OS Used: macOS Catalina Version 10.15.3
Java Version: 8 Update 241 (build 1.8.0_241-b07)
Release: Peer Assessment 3 
Severity: Normal
Priority: P3

Steps to Reproduce: 
1. Open Venn Application
2. Type some text and click Add
3. Drag and drop item in top right corner of the left circle

Actual Results: The item drops into the middle circle rather than dropping into the left circle. 
Expected Results: The item should drop into the left circle rather than dropping into the middle circle.

**Comment by MohaimenH** [comment]
Thanks for your feedback.

The new version is completely based on drag and drop, hence the bug is not present anymore.

Fixed and closed.
