### ISSUE TITLE
(Bug) Putting a space before text

### ISSUE THREAD

**Issue by gill-indermohan-216542045** [MohaimenH/Venn#27]
OS used: Mac
Release Tested: Latest Release
Java Version: Java 13
Description: Putting a space before a text will make the text different from the same text without the space at the beginning.
Severity: Small
Priority: P3

Steps to Produce: Open the app, add a text with no space before it, then add another text with the same text as before but press space before it.

Expected Result: The diagram treats the 2 texts as the same text.

Actual Result: The app allows both texts to exist in the same circle.
![image](https://user-images.githubusercontent.com/46453971/76714095-99b7b780-66fb-11ea-888e-0e19644827b7.png)

**Comment by MohaimenH** [comment]
Thanks for the feedback.

Whitespace is considered to be a character, making the strings unique.
