### ISSUE TITLE
(Enhancement) Changing Font Size and Font of Text in the Circles

### ISSUE THREAD

**Issue by gill-indermohan-216542045** [MohaimenH/Venn#28]
OS used: Mac
Release Tested: Latest Release
Java Version: Java 13
Description: Allow text customizability for the text in the circles. Would allow user to change the font of the text or the font size of the text as is possible for the labels and title.
Severity: Normal
Priority: P3

Steps to Produce: Open the app, add a text to the circles, then either right-click the text or go to the “Edit” menu to make the changes

Expected Result: Change font and/or font size of the text in the circles.

Actual Result: No customizability for the text in the circles.

**Comment by MohaimenH** [comment]
Thanks for your feedback.

The features were added to the new version. 

Closed.
