### ISSUE TITLE
Import text files into the list

### ISSUE THREAD

**Issue by MohaimenH** [MohaimenH/Venn#9]
Be able to import two different lists so that they can be compared.

**Comment by MohaimenH** [comment]
Importing text documents work now. Next improvement would be to import text documents formatted in a certain way, so that it directly goes on to the Venn diagram, allowing users to share their Venn diagrams for others to use.

**Comment by li-jiahao-216263949** [comment]
> Importing text documents work now. Next improvement would be to import text documents formatted in a certain way, so that it directly goes on to the Venn diagram, allowing users to share their Venn diagrams for others to use.

Issue resolved.
